### ISSUE TITLE
unexpected status: 500 Internal Server Error when image built and push with moby/buildkit 

### ISSUE THREAD

**Issue by labradorcode** [pulp/pulp_container#1131]
**Version**
`pulpcore 3.21.2`
`python 3.7.3`
`pulp-container 2.14.2`
`moby/buildkit:latest/master/v0.10.5`

**Describe the bug**
When I'm trying build a multi-arch image and push to pulp using **moby/buildkit** pulp returns with 500 Internal Error

**To Reproduce**
```
docker buildx ls
NAME/NODE  DRIVER/ENDPOINT              STATUS  BUILDKIT PLATFORMS
builder *  remote                                        
  builder0 docker-container://buildkitd running          linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
default    docker                                        
  default  default                      running 20.10.21 linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```
```
docker ps
CONTAINER ID   IMAGE                    COMMAND       CREATED          STATUS          PORTS                                       NAMES
ede3891483ed   moby/buildkit:v0.10.3    "buildkitd"   33 minutes ago   Up 32 minutes                                               buildkitd

```

docker image build command

`docker buildx build --platform=linux/amd64,linux/arm64 --push -t test .`

returns with

```
[+] Building 10.9s (9/9) FINISHED                                                                                                                                                                                  
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 601B                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/alpine:edge                                                                                                                                                0.4s
 => [1/4] FROM docker.io/library/alpine:edge@sha256:69361f5f421bb47db6f2f6baf84ab50b8f7c9b209f8376048dda955535224be8                                                                                          0.0s
 => => resolve docker.io/library/alpine:edge@sha256:69361f5f421bb47db6f2f6baf84ab50b8f7c9b209f8376048dda955535224be8                                                                                          0.0s
 => [internal] load build context                                                                                                                                                                             0.0s
 => => transferring context: 71B                                                                                                                                                                              0.0s
 => CACHED [2/4] RUN apk add --no-cache     php81     php81-curl     libjpeg     php81-mbstring     php81-pecl-imagick     php81-gd     cups-client     supervisor                                            0.0s
 => CACHED [3/4] RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing htmldoc                                                                                                          0.0s
 => CACHED [4/4] ADD ./config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf                                                                                                                        0.0s
 => ERROR exporting to image                                                                                                                                                                                 10.4s
 => => exporting layers                                                                                                                                                                                       0.0s
 => => exporting manifest sha256:8a70f8d041fa1e8e55aa28f80f2e74cd93b8c6ce4920ca736ccdf9a9f919696b                                                                                                             0.0s
 => => exporting config sha256:1afeef6bd3514dc1e25f4839cd9638c4fabe15c450b2bf1d763ab358da1af3c9                                                                                                               0.0s
 => => pushing layers                                                                                                                                                                          10.4s
exporting to image:                                                                                                                                                                                             
#0 0.546 error: failed commit on ref "config-sha256:1afeef6bd3514dc1e25f4839cd9638c4fabe15c450b2bf1d763ab358da1af3c9": unexpected status: 500 Internal Server Error                                                
#0 0.546 retrying in 1s                                                                                                                                                                                            
#0 0.697 error: failed commit on ref "layer-sha256:fb0e15f4884fc50ebe74881aa2411785dc5ce4b99f504cf2cb393d8d2ccc1924": unexpected status: 500 Internal Server Error                                                 
#0 0.698 retrying in 1s                                                                                                                                                                                            
#0 0.892 error: failed commit on ref "layer-sha256:1b9c26f34f201e5a429e2768230ccde740a6fa9bd76890bce5c7e16ccb262e81": unexpected status: 500 Internal Server Error
#0 0.892 retrying in 1s
#0 1.371 error: failed commit on ref "layer-sha256:a0bedf5fb0b186918d58b2d3e407b2504d73dd784fac09fbb782e259aab8c46a": unexpected status: 500 Internal Server Error
#0 1.371 retrying in 1s
#0 1.748 error: failed commit on ref "config-sha256:1afeef6bd3514dc1e25f4839cd9638c4fabe15c450b2bf1d763ab358da1af3c9": unexpected status: 500 Internal Server Error
#0 1.748 retrying in 2s
#0 1.926 error: failed commit on ref "layer-sha256:fb0e15f4884fc50ebe74881aa2411785dc5ce4b99f504cf2cb393d8d2ccc1924": unexpected status: 500 Internal Server Error
#0 1.926 retrying in 2s
#0 2.159 error: failed commit on ref "layer-sha256:1b9c26f34f201e5a429e2768230ccde740a6fa9bd76890bce5c7e16ccb262e81": unexpected status: 500 Internal Server Error
#0 2.159 retrying in 2s
#0 3.377 error: failed commit on ref "layer-sha256:a0bedf5fb0b186918d58b2d3e407b2504d73dd784fac09fbb782e259aab8c46a": unexpected status: 500 Internal Server Error
#0 3.377 retrying in 2s
#0 3.934 error: failed commit on ref "config-sha256:1afeef6bd3514dc1e25f4839cd9638c4fabe15c450b2bf1d763ab358da1af3c9": unexpected status: 500 Internal Server Error
#0 3.934 retrying in 4s
#0 4.125 error: failed commit on ref "layer-sha256:fb0e15f4884fc50ebe74881aa2411785dc5ce4b99f504cf2cb393d8d2ccc1924": unexpected status: 500 Internal Server Error
#0 4.125 retrying in 4s
#0 4.394 error: failed commit on ref "layer-sha256:1b9c26f34f201e5a429e2768230ccde740a6fa9bd76890bce5c7e16ccb262e81": unexpected status: 500 Internal Server Error
#0 4.394 retrying in 4s
#0 6.407 error: failed commit on ref "layer-sha256:a0bedf5fb0b186918d58b2d3e407b2504d73dd784fac09fbb782e259aab8c46a": unexpected status: 500 Internal Server Error
#0 6.407 retrying in 4s
#0 8.125 error: failed commit on ref "config-sha256:1afeef6bd3514dc1e25f4839cd9638c4fabe15c450b2bf1d763ab358da1af3c9": unexpected status: 500 Internal Server Error
ERROR: failed to solve: failed commit on ref "config-sha256:1afeef6bd3514dc1e25f4839cd9638c4fabe15c450b2bf1d763ab358da1af3c9": unexpected status: 500 Internal Server Error

```

**output from pulp logs**
```
[74970784fb774715921bf67dc10e7ee0]: 127.0.0.1 - - [01/Nov/2022:13:53:04 +0000] "PUT /v2/redacted/blobs/uploads/20c9ab23-a790-4eb4-ba00-d60845ced442?digest=sha256%3Aef84036aa7625cbdfe841fafc68508ccfdbad6ed977ac7284ff583e9edc9c8a9 HTTP/1.0" 500 145 "-" "buildkit/v0.10"
[66e597a572804322a2974c6fa378ac79]: django.request:WARNING: Not Found: /v2/redacted/blobs/sha256:972e6ef884e53a5f7306dc6585b7dbef04608fb9405fb2aedd38096366ac30a4
[66e597a572804322a2974c6fa378ac79]: 127.0.0.1 - - [01/Nov/2022:13:53:04 +0000] "HEAD /v2/redacted/blobs/sha256:972e6ef884e53a5f7306dc6585b7dbef04608fb9405fb2aedd38096366ac30a4 HTTP/1.0" 404 158 "-" "buildkit/v0.10"
[239b349ef3a74b7e9d6aadda1a5804d3]: 127.0.0.1 - - [01/Nov/2022:13:53:04 +0000] "POST /v2/redacted/blobs/uploads/ HTTP/1.0" 202 0 "-" "buildkit/v0.10"
[ddf54a243f2e4799bd74d09389e08982]: django.request:WARNING: Not Found: /v2/redacted/blobs/sha256:b26bcb0b4610e60bfc0643378cd1c3dd42a8fee735c60c36ae7d3a7f8bed9600
[ddf54a243f2e4799bd74d09389e08982]: 127.0.0.1 - - [01/Nov/2022:13:53:04 +0000] "HEAD /v2/redacted/blobs/sha256:b26bcb0b4610e60bfc0643378cd1c3dd42a8fee735c60c36ae7d3a7f8bed9600 HTTP/1.0" 404 158 "-" "buildkit/v0.10"
[12b24f4eb4914132bb24030e125c8f27]: django.request:ERROR: Internal Server Error: /v2/redacted/blobs/uploads/fecc8b44-6ffe-4512-810d-fabd13db0350
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/pulp_container/app/registry_api.py", line 259, in handle_exception
    response = super().handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pulp_container/app/registry_api.py", line 735, in put
    raise Exception("The digest did not match")
Exception: The digest did not match
[12b24f4eb4914132bb24030e125c8f27]: 127.0.0.1 - - [01/Nov/2022:13:53:04 +0000] "PUT /v2/redacted/blobs/uploads/fecc8b44-6ffe-4512-810d-fabd13db0350?digest=sha256%3A972e6ef884e53a5f7306dc6585b7dbef04608fb9405fb2aedd38096366ac30a4 HTTP/1.0" 500 145 "-" "buildkit/v0.10"
[9c57fd182313495286c6bcc195226d16]: 127.0.0.1 - - [01/Nov/2022:13:53:04 +0000] "POST /v2/redacted/blobs/uploads/ HTTP/1.0" 202 0 "-" "buildkit/v0.10"
[a89b08c33f77479cbf0ca0c85a0e7d81]: 127.0.0.1 - - [01/Nov/2022:13:53:04 +0000] "HEAD /v2/redacted/blobs/sha256:1c00945152f549b64d7109e5cfa9c1a9d8293da7ae0ce535f674e7af72837bdf HTTP/1.0" 404 158 "-" "buildkit/v0.10"
[a89b08c33f77479cbf0ca0c85a0e7d81]: django.request:WARNING: Not Found: /v2/redacted/blobs/sha256:1c00945152f549b64d7109e5cfa9c1a9d8293da7ae0ce535f674e7af72837bdf
```

this issue doesn't occur with native docker buildkit, but native doesn't support multi-arch image manifest 

**Expected behavior**
push multi-arch image

**Comment by ipanova** [comment]
@labradorcode did you try building multi arch images with podman?

**Comment by labradorcode** [comment]
> @labradorcode did you try building multi arch images with podman?

Got it! Works perfect with podman! 

any idea why is not working with moby buildkit?
