### ISSUE TITLE
An error is raised when using pull-through caching in a disconnected environment

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulp_container#1499]
This happens when using the pull-through caching workflow with no internet connection.

Traceback:
```
pulp [None]: backoff:ERROR: Giving up download_wrapper(...) after 4 tries (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host registry-1.docker.io:443 ssl:default [Name or service not known])
[2024-02-03 17:20:47 +0000] [6911] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/src/pulpcore/pulpcore/content/authentication.py", line 48, in authenticate
    return await handler(request)
  File "/src/pulpcore/pulpcore/content/instrumentation.py", line 230, in middleware
    resp = await handler(request)
  File "/src/pulp_container/pulp_container/app/registry.py", line 158, in get_tag
    response = await downloader.run(
  File "/src/pulpcore/pulpcore/download/http.py", line 269, in run
    return await download_wrapper()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/src/pulpcore/pulpcore/download/http.py", line 254, in download_wrapper
    return await self._run(extra_data=extra_data)
  File "/src/pulp_container/pulp_container/app/downloaders.py", line 79, in _run
    async with session_http_method(
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib64/python3.8/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host registry-1.docker.io:443 ssl:default [Name or service not known]
```

**Comment by lubosmj** [comment]
The following change fixes the error on the pulp-container's side. However, there still a 10s timeout defined somewhere that holds the whole process unresponsive. Maybe, the problem is here: https://github.com/pulp/pulpcore/blob/229766a1b746215035ff16d3577f2a0dbf5de22b/pulpcore/download/http.py#L163-L167?

```diff
--- a/pulp_container/app/registry.py
+++ b/pulp_container/app/registry.py
@@ -8,7 +8,7 @@ from contextlib import suppress
 from urllib.parse import urljoin
 
 from aiohttp import web
-from aiohttp.client_exceptions import ClientResponseError
+from aiohttp.client_exceptions import ClientResponseError, ClientConnectionError
 from aiohttp.web_exceptions import HTTPTooManyRequests
 from django_guid import set_guid
 from django_guid.utils import generate_guid
@@ -154,11 +154,12 @@ class Registry(Handler):
             )
             tag_url = urljoin(remote.url, relative_url)
             downloader = remote.get_downloader(url=tag_url)
+            downloader.max_retries = 0
             try:
                 response = await downloader.run(
-                    extra_data={"headers": V2_ACCEPT_HEADERS, "http_method": "head"}
+                    extra_data={"headers": V2_ACCEPT_HEADERS, "http_method": "head"},
                 )
-            except ClientResponseError:
+            except (ClientResponseError, ClientConnectionError):
                 # the manifest is not available on the remote anymore
                 # but the old one is still stored in the database
                 pass
diff --git a/pulp_container/app/registry_api.py b/pulp_container/app/registry_api.py
index fe0e5662..fbb903dc 100644
--- a/pulp_container/app/registry_api.py
+++ b/pulp_container/app/registry_api.py
@@ -11,7 +11,7 @@ import logging
 import hashlib
 import re
 
-from aiohttp.client_exceptions import ClientResponseError
+from aiohttp.client_exceptions import ClientResponseError, ClientConnectionError
 from itertools import chain
 from urllib.parse import urljoin, urlparse, urlunparse, parse_qs, urlencode
 from tempfile import NamedTemporaryFile
@@ -1098,6 +1098,7 @@ class Manifests(RedirectsMixin, ContainerRegistryApiMixin, ViewSet):
         )
         tag_url = urljoin(remote.url, relative_url)
         downloader = remote.get_downloader(url=tag_url)
+        downloader.max_retries = 0
         try:
             response = downloader.fetch(
                 extra_data={"headers": V2_ACCEPT_HEADERS, "http_method": "head"}
@@ -1110,6 +1111,9 @@ class Manifests(RedirectsMixin, ContainerRegistryApiMixin, ViewSet):
             else:
                 # TODO: do not mask out relevant errors, like HTTP 502
                 raise ManifestNotFound(reference=pk)
+        except ClientConnectionError:
+            # The remote server is not available
+            raise ManifestNotFound(reference=pk)
         else:
             digest = response.headers.get("docker-content-digest")
             return models.Manifest.objects.filter(digest=digest).first()
```

**Comment by lubosmj** [comment]
Changing this configuration in pulpcore helped to resolve the problem: https://github.com/pulp/pulpcore/blob/229766a1b746215035ff16d3577f2a0dbf5de22b/pulpcore/download/factory.py#L134-L139.

It might be worth considering adding a migration that set timeouts and backoffs to correct value for pull-through caching remotes.

**Comment by lubosmj** [comment]
I am waiting to get this merged: https://github.com/pulp/pulpcore/pull/5025.

**Comment by ipanova** [comment]
I would except similar traceback would be shown also during regular sync. None of these features are designed to work on air gapped env.

**Comment by ipanova** [comment]
It makes sense to deliver content which is already locally cached, however for the cases when pulp instance needs to reach out to the internet whether during the first pull or during sync we should not raise 404 but propagate the error.

**Comment by lubosmj** [comment]
Yes, with the change, we should also refactor the following code paths:
https://github.com/pulp/pulp_container/blob/59e06e591bd3e621401d83f417fd3fa2ecadbf0a/pulp_container/app/registry_api.py#L1111
https://github.com/pulp/pulp_container/blob/59e06e591bd3e621401d83f417fd3fa2ecadbf0a/pulp_container/app/registry.py#L429

**Comment by lubosmj** [comment]
`TimeoutException` can be consumed by plugin writers as of pulpcore 3.46.0 (2024-02-13).
