### ISSUE TITLE
pulpcore worker does not start after upgrade to 2.11

### ISSUE THREAD

**Issue by ipanova** [pulp/pulp_container#640]
**Version**
Please provide the versions of the pulpcore and pulp_container packages in use, and how they are installed.  If you are using Pulp via Katello, please provide the Katello version.

**Describe the bug**
```
Starting gunicorn 20.1.0
Listening at: http://127.0.0.1:9000/ (522413)
Using worker: sync
Booting worker with pid: 522415
/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/redis/[connection.py:72](http://connection.py:72/): UserWarning: redis-py works best with hiredis. Please consider installing
  warnings.warn(msg)
[2022-03-17 10:10:16 +0000] [522415] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/[gnupg.py](http://gnupg.py/)", line 881, in __init__
    p = self._open_subprocess(["--version"])
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/[gnupg.py](http://gnupg.py/)", line 961, in _open_subprocess
    result = Popen(cmd, shell=False, stdin=PIPE, stdout=PIPE, stderr=PIPE,
  File "/usr/lib64/python3.8/[subprocess.py](http://subprocess.py/)", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.8/[subprocess.py](http://subprocess.py/)", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gpg'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/gunicorn/[arbiter.py](http://arbiter.py/)", line 589, in spawn_worker
    worker.init_process()
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/gunicorn/workers/[base.py](http://base.py/)", line 134, in init_process
    self.load_wsgi()
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/gunicorn/workers/[base.py](http://base.py/)", line 146, in load_wsgi
    self.wsgi = [self.app](http://self.app/).wsgi()
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/gunicorn/app/[base.py](http://base.py/)", line 67, in wsgi
    self.callable = self.load()
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/gunicorn/app/[wsgiapp.py](http://wsgiapp.py/)", line 58, in load
    return self.load_wsgiapp()
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/gunicorn/app/[wsgiapp.py](http://wsgiapp.py/)", line 48, in load_wsgiapp
    return util.import_app([self.app](http://self.app/)_uri)
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/gunicorn/[util.py](http://util.py/)", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/pulpcore/app/[wsgi.py](http://wsgi.py/)", line 17, in <module>
    application = get_wsgi_application()
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/django/core/[wsgi.py](http://wsgi.py/)", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/django/apps/[registry.py](http://registry.py/)", line 114, in populate
    app_config.import_models()
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/django/apps/[config.py](http://config.py/)", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/pulp_container/app/[models.py](http://models.py/)", line 41, in <module>
    gpg = gnupg.GPG()
  File "/var/lib/pulp/pulpvenv/lib64/python3.8/site-packages/[gnupg.py](http://gnupg.py/)", line 885, in __init__
    raise OSError(msg)
OSError: Unable to run gpg (gpg) - it may not be available.
Worker exiting (pid: 522415)
Shutting down: Master
Reason: Worker failed to boot.
```

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by ipanova** [comment]
it seems like we need to provide gpgbinary

**Comment by lubosmj** [comment]
We need to make the `gpgbinary` parameter configurable for all occurrences of `gpg = gnupg.GPG()`. I suggest introducing a new pulp setting called `GPG_BINARY_PATH` that will be promoted in pulpcore (https://github.com/pulp/pulpcore/search?q=gnupg).
